services:
  app:
    build:
      context: server
      dockerfile: Dockerfile
    env_file: .env
    environment:
      DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MYSQL_PORT}/${MYSQL_DATABASE}"
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./server:/app
      - /app/target/debug
    tty: true
    stdin_open: true
    depends_on:
      - db

  db:
    image: mysql:8
    command: >
      --log-bin-trust-function-creators=1
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: UTC
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    volumes:
      - db:/var/lib/mysql
    platform: linux/arm64

  cert:
    build:
      context: server
      dockerfile: Dockerfile.cert
    working_dir: /work
    volumes:
      - .:/work

volumes:
  db:
